twitter-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Spring
    - Elasticsearch
  welcome-message: "Welcome to the Twitter Kafka Service!"
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

  retry-config:
    max-attempts: 3
    initial-interval: 1000
    max-interval: 10000
    multiplier: 2.0
    sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3

